typography_spectrum: 0.6564055283088237
color:
  brandStrength: 0.15295741544105113
  lightness: 0.9430538166780025
  saturation: 0.03416904644109309
  rhythmicContrast: 0.24410077440552413
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.7789505438413471
name: POETREE TEST
navigation:
  - name: Let's connect on LinkedIn
    url: 'https://www.linkedin.com/in/roupertmuller'
    type: external
title: Digital Agency
description: All about performance
